# ============================================================================
# 🐳 DOCKER COMPOSE - AMBIENTE COMPLETO RESULTADOS
# ============================================================================
# 
# Orquestração completa do microserviço resultados:
# - MySQL 8.0 com R2DBC
# - Redis para cache distribuído  
# - Prometheus para métricas
# - Grafana para dashboards
# - Volumes persistentes
# - Rede isolada
# 
# Uso: docker-compose up -d
# ============================================================================

version: '3.9'

services:
  # ========================================
  # 📊 MICROSERVIÇO RESULTADOS
  # ========================================
  resultados-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resultados-microservice
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      # Azure OIDC Configuration
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_KEYVAULT_ENDPOINT=${AZURE_KEYVAULT_ENDPOINT}
      - AZURE_KEYVAULT_NAME=${AZURE_KEYVAULT_NAME:-kv-conexao-de-sorte}
      
      # Database (fallbacks para desenvolvimento local)
      - conexao_de_sorte_database_url=${conexao_de_sorte_database_url:-r2dbc:mysql://resultados-mysql:3306/conexao_sorte_resultados?useSSL=true&allowPublicKeyRetrieval=true}
      - conexao_de_sorte_database_username=${conexao_de_sorte_database_username:-resultados_user}
      - conexao_de_sorte_database_password=${conexao_de_sorte_database_password:-}
      
      # Redis (fallbacks para desenvolvimento local)
      - conexao_de_sorte_redis_host=${conexao_de_sorte_redis_host:-resultados-redis}
      - conexao_de_sorte_redis_port=${conexao_de_sorte_redis_port:-6379}
      - conexao_de_sorte_redis_password=${conexao_de_sorte_redis_password:-}
      
      # JWT (segredos Azure Key Vault)
      - conexao_de_sorte_jwt_jwks_uri=${conexao_de_sorte_jwt_jwks_uri:-http://autenticacao-service:8081/.well-known/jwks.json}
      - conexao_de_sorte_jwt_issuer=${conexao_de_sorte_jwt_issuer:-https://auth.conexaodesorte.com}
      - conexao_de_sorte_jwt_secret=${conexao_de_sorte_jwt_secret:-}
      - conexao_de_sorte_jwt_key_id=${conexao_de_sorte_jwt_key_id:-}
      
      # Features
      - FEATURE_RESULTADOS_MS=true
      - FEATURE_ADVANCED_RANKING=true
      - FEATURE_STATS_CACHE=true
      - FEATURE_AUDIT_LOGGING=true
      - FEATURE_METRICS=true
      
      # Observability
      - TRACING_PROBABILITY=1.0
      - LOG_LEVEL=INFO
      
      # Performance
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    depends_on:
      - resultados-mysql
      - resultados-redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - conexao-network
    volumes:
      - ./logs:/app/logs

# ========================================
# 💾 VOLUMES PERSISTENTES
# ========================================
volumes:
  resultados-mysql-data:
    driver: local
  resultados-redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

# ========================================
# 🌐 REDE ISOLADA
# ========================================
networks:
  conexao-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
