version: '3.9'

services:
  resultados:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: conexao-resultados
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      RESULTADOS_LOG_LEVEL: "INFO"
    networks:
      - conexao-network-swarm
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  resultados_data:
    name: conexao_resultados_data

networks:
  conexao-network-swarm:
    name: conexao-network-swarm
    external: true
