services:
  conexao-de-sorte-backend-resultados:
    image: wibson82/conexao-de-sorte-backend-resultados:latest
    container_name: conexao-de-sorte-backend-resultados

    # OTIMIZAÇÃO HOSTINGER KVM 2
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400m
        reservations:
          cpus: '0.1'
          memory: 128m
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s

    # Configurações otimizadas
    restart: unless-stopped

    # Health check leve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s

    # Variáveis de ambiente JVM otimizadas e secrets
    environment:
      - JAVA_OPTS=-Xms128m -Xmx350m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication
      - SERVER_PORT=8087
      - SPRING_PROFILES_ACTIVE=prod
      # Secrets expostos como variáveis de ambiente (R2DBC ONLY)
      - CONEXAO_DE_SORTE_DATABASE_PASSWORD_FILE=/run/secrets/conexao-de-sorte-database-password
      - CONEXAO_DE_SORTE_DATABASE_USERNAME_FILE=/run/secrets/conexao-de-sorte-database-username
      - CONEXAO_DE_SORTE_DATABASE_R2DBC_URL_FILE=/run/secrets/conexao-de-sorte-database-r2dbc-url
      - CONEXAO_DE_SORTE_REDIS_PASSWORD_FILE=/run/secrets/conexao-de-sorte-redis-password
      - CONEXAO_DE_SORTE_JWT_SECRET_FILE=/run/secrets/conexao-de-sorte-jwt-secret

    # Secrets via Docker Swarm
    secrets:
      - conexao-de-sorte-database-password
      - conexao-de-sorte-database-username
      - conexao-de-sorte-database-r2dbc-url
      - conexao-de-sorte-redis-password
      - conexao-de-sorte-jwt-secret

    # Networks
    networks:
      - conexao-network-swarm

    # Logging otimizado
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Secrets externos
secrets:
  conexao-de-sorte-database-password:
    external: true
  conexao-de-sorte-database-username:
    external: true
  conexao-de-sorte-database-r2dbc-url:
    external: true
  conexao-de-sorte-redis-password:
    external: true
  conexao-de-sorte-jwt-secret:
    external: true

# Networks externos
networks:
  conexao-network-swarm:
    external: true
