spring:
  application:
    name: resultados
    
  profiles:
    active: dev
  
  # Configtree secret management
  config:
    import:
      - optional:configtree:/etc/secrets/azure/
      - optional:configtree:/mnt/secrets/
      - optional:file:./secrets.properties
    
  r2dbc:
    url: r2dbc:mysql://localhost:3306/conexao_sorte_resultados
    username: ${DB_USERNAME:conexao_sorte}
    password: ${DB_PASSWORD:}  # Removed default password for security
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 60s
      
  # Flyway para migrations (usa JDBC)
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/conexao_sorte_resultados
    user: ${DB_USERNAME:conexao_sorte}
    password: ${DB_PASSWORD:}  # Removed default password for security
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    
  # Cache reativo (Redis)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          enabled: true
          max-active: 20
          max-idle: 8
          min-idle: 2
          
  # Security JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWKS_URI:http://localhost:8081/.well-known/jwks.json}
          issuer-uri: ${JWT_ISSUER:https://auth.conexaodesorte.com}

server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful
  
  # SSL/TLS Configuration
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE_PATH:}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: PKCS12
    
  netty:
    connection-timeout: 20s
    h2c-max-content-length: 0B
    
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: GET
        
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
      probes:
        enabled: true
        
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
      
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60s
    web:
      server:
        request:
          autotime:
            enabled: true
            percentiles: 0.5,0.95,0.99
            
  tracing:
    enabled: true
    sampling:
      probability: ${TRACING_PROBABILITY:0.1}

# Paginação e Performance
pagination:
  default-size: 20
  max-size: 100
  default-sort: dataResultado,desc
  
# Cache Configuration
cache:
  resultados:
    ttl: 300  # 5 minutos
  ranking:
    ttl: 900  # 15 minutos
  estatisticas:
    ttl: 1800  # 30 minutos

# CORS Configuration
cors:
  # Origens permitidas para requisições. Utilize "*" apenas em desenvolvimento.
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Rate Limiting
rate-limit:
  enabled: true
  default-requests-per-minute: 120
  endpoints:
    "/api/resultados":
      requests-per-minute: 60
      burst-capacity: 100
    "/api/resultados/ranking":
      requests-per-minute: 30
      burst-capacity: 50
    "/api/resultados/estatisticas":
      requests-per-minute: 20
      burst-capacity: 30

# Security Headers
security:
  headers:
    content-security-policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'"
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-xss-protection: "1; mode=block"
    strict-transport-security: "max-age=31536000; includeSubDomains"

# Feature Flags
features:
  resultados-microservice: ${FEATURE_RESULTADOS_MS:false}
  advanced-ranking: ${FEATURE_ADVANCED_RANKING:true}
  statistics-cache: ${FEATURE_STATS_CACHE:true}
  audit-logging: ${FEATURE_AUDIT_LOGGING:true}
  metrics-collection: ${FEATURE_METRICS:true}

# Logging Configuration
logging:
  level:
    br.tec.facilitaservicos.resultados: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.springframework.r2dbc: ${R2DBC_LOG_LEVEL:WARN}
    io.r2dbc.mysql: ${MYSQL_LOG_LEVEL:WARN}
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    
  file:
    name: ${LOG_FILE:logs/resultados.log}

# OpenAPI Documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false
  
# Resilience4j Configuration
resilience4j:
  ratelimiter:
    instances:
      resultados-service:
        limit-for-period: 60
        limit-refresh-period: 1m
        timeout-duration: 3s
        
  circuitbreaker:
    instances:
      database:
        sliding-window-size: 100
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
      
  r2dbc:
    url: r2dbc:mysql://localhost:3306/conexao_sorte_resultados_dev
    
  flyway:
    url: jdbc:mysql://localhost:3306/conexao_sorte_resultados_dev
    
logging:
  level:
    br.tec.facilitaservicos.resultados: DEBUG
    org.springframework.security: DEBUG
    org.springframework.r2dbc: DEBUG
    
features:
  resultados-microservice: true
  audit-logging: true
  metrics-collection: true

---
# Test Profile  
spring:
  config:
    activate:
      on-profile: test
      
  r2dbc:
    url: r2dbc:mysql://localhost:3306/conexao_sorte_resultados_test
    
  flyway:
    url: jdbc:mysql://localhost:3306/conexao_sorte_resultados_test
    clean-disabled: false
    
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
          
logging:
  level:
    br.tec.facilitaservicos.resultados: DEBUG
    
features:
  resultados-microservice: true
  metrics-collection: false

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
      
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:conexao_sorte_resultados}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 20
      max-size: 100
      
  flyway:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:conexao_sorte_resultados}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
server:
  port: 8082
  ssl:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
      
logging:
  level:
    br.tec.facilitaservicos.resultados: INFO
    root: WARN
    
  file:
    name: /var/log/resultados/application.log
    
features:
  resultados-microservice: true
  advanced-ranking: true
  statistics-cache: true
  audit-logging: true
  metrics-collection: true
  
rate-limit:
  default-requests-per-minute: 60
  endpoints:
    "/api/resultados":
      requests-per-minute: 30