# =============================================================================
# Production profile without fallbacks/placeholders
# All sensitive values must come from configtree (/run/secrets) or env-injected properties
# =============================================================================

spring:
  config:
    import:
      - optional:configtree:/run/secrets/

  r2dbc:
    url: ${conexao-de-sorte-database-url:r2dbc:mysql://conexao-mysql:3306/conexao_sorte_resultados?useSSL=true&allowPublicKeyRetrieval=true}
    username: ${conexao-de-sorte-database-username:}
    password: ${conexao-de-sorte-database-password:}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 60s

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  # Redis configurado via Azure Key Vault - não excluir autoconfiguração
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

server:
  shutdown: graceful
