# =============================================================================
# Production profile without fallbacks/placeholders
# All sensitive values must come from configtree (/run/secrets) or env-injected properties
# =============================================================================

spring:
  config:
    import:
      - optional:configtree:/run/secrets/

  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 60s

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

server:
  shutdown: graceful
