spring:
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    redis:
      host: false
  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  
  flyway:
    enabled: false
    
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

logging:
  level:
    br.tec.facilitaservicos: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
features:
  statistics-cache: false

app:
  cors:
    allowed-origins: http://localhost:3000
  rate-limit:
    requests-per-minute: 1000
  cache:
    ttl:
      resultados: PT5M
      ranking: PT1H
