# =============================================================================
# CONFIGURAÇÃO AZURE KEY VAULT - SOLUÇÃO HÍBRIDA OIDC - RESULTADOS MICROSERVICE
# =============================================================================
# ✅ Solução Híbrida OIDC implementada:
# ✅ CI/CD: GitHub Actions usa OIDC puro para buscar secrets
# ✅ Runtime: Container usa Client Credentials com secrets injetados  
# ✅ Zero configuração no servidor Ubuntu (funciona em qualquer ambiente)
# ✅ Secrets nunca persistem no servidor (máxima segurança)
# =============================================================================

spring:
  config:
    activate:
      on-profile: azure
    import:
      - "optional:configtree:/run/secrets/"
      - "optional:classpath:application-prod.yml"

  # ===== SPRING CLOUD AZURE DESABILITADO =====
  # Usando configuração customizada em AzureKeyVaultConfig
  cloud:
    compatibility-verifier:
      enabled: false


  # ===== DATABASE CONFIGURATION (R2DBC REATIVO) =====
  # Segredos vindos do Azure Key Vault via R2dbcUrlNormalizer (programação defensiva)
  # URLs JDBC são automaticamente convertidas para R2DBC
  r2dbc:
    # Preferencialmente usa -database-r2dbc-url; mantém compat com -database-url
    url: ${conexao-de-sorte-database-r2dbc-url:${conexao-de-sorte-database-url:r2dbc:mysql://mysql-proxy:6033/conexao_sorte_resultados?useSSL=true&allowPublicKeyRetrieval=false}}
    username: ${conexao-de-sorte-database-username:}
    password: ${conexao-de-sorte-database-password:}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 60s

  # ===== FLYWAY CONFIGURATION (JDBC para migrations) =====
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  # ===== REDIS CONFIGURATION =====
  data:
    redis:
      host: ${conexao-de-sorte-redis-host:conexao-redis}
      port: ${conexao-de-sorte-redis-port:6379}
      password: ${conexao-de-sorte-redis-password:}
      database: ${conexao-de-sorte-redis-database:2}  # DB 2 para resultados
      timeout: 2000ms
      lettuce:
        pool:
          enabled: true
          max-active: 20
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms



  # ===== SECURITY JWT CONFIGURATION =====
  security:
    oauth2:
      resourceserver:
        jwt:
          # Configuração para validação de tokens (não geração)
          jwk-set-uri: ${conexao-de-sorte-jwt-jwks-uri:http://conexao-auth:8081/.well-known/jwks.json}
          issuer-uri: ${conexao-de-sorte-jwt-issuer:https://auth.conexaodesorte.com}

# ===== APLICAÇÃO ESPECÍFICA =====
aplicacao:
  microservico:
    nome: resultados
    versao: "1.0.0"
    descricao: "Microserviço de gerenciamento de resultados de loteria"
  
  # Configuração JWT adicional - Segredos do Azure Key Vault
  jwt:
    # Chaves para validação (não geração)
    chave-assinatura: ${conexao-de-sorte-jwt-signing-key:}
    chave-verificacao: ${conexao-de-sorte-jwt-verification-key:}
    id-chave: ${conexao-de-sorte-jwt-key-id:}
    segredo: ${conexao-de-sorte-jwt-secret:}
    chave-publica: ${conexao-de-sorte-jwt-publickey:}
    chave-privada: ${conexao-de-sorte-jwt-privatekey:}
    emissor: https://conexaodesorte.com.br
    audiencia: conexao-de-sorte-frontend-app
    algoritmo: RS256
    # Configurações específicas para consumo de tokens
    validacao:
      habilitado: true
      modo-estrito: true
      requer-expiracao: true
      desvio-relogio: PT30S

  # Configuração de Criptografia - Segredos do Azure Key Vault
  criptografia:
    chave-mestra: ${conexao-de-sorte-encryption-master-key:}
    senha-mestra: ${conexao-de-sorte-encryption-master-password:}
    chave-backup: ${conexao-de-sorte-encryption-backup-key:}
    algoritmo: AES-256-GCM
    rotacao-chaves: P30D # 30 dias

  # Cache Configuration
  cache:
    habilitado: true
    ttl:
      resultados: PT5M
      ranking: PT1H
      estatisticas: PT10M

  # Rate Limiting
  limite-taxa:
    requisicoes-por-minuto: 100
    capacidade-rajada: 50

# ===== AZURE LOGGING =====
logging:
  level:
    '[com.azure]': INFO
    '[com.azure.security.keyvault]': INFO
    '[org.springframework.cloud.azure]': INFO
    '[br.tec.facilitaservicos.resultados]': INFO

# ===== MANAGEMENT ENDPOINTS (HARDENED) =====
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
        exclude: env,configprops,beans,conditions,mappings,threaddump,heapdump,startup
      base-path: /actuator
      cors:
        allowed-origins: "https://monitoring.conexaodesorte.com.br"
        allowed-methods: GET
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
    env:
      enabled: false
    configprops:
      enabled: false
    beans:
      enabled: false
    conditions:
      enabled: false
    mappings:
      enabled: false
    threaddump:
      enabled: false
    heapdump:
      enabled: false
  health:
    keyvault:
      enabled: true
    db:
      enabled: true
    redis:
      enabled: true
  # Security for actuator endpoints
  security:
    enabled: true
    roles: ACTUATOR

# ===== CONFIGURAÇÃO AZURE KEY VAULT HÍBRIDA =====
azure:
  keyvault:
    enabled: ${AZURE_KEYVAULT_ENABLED:true}
    endpoint: ${AZURE_KEYVAULT_ENDPOINT:}
    client-id: ${AZURE_CLIENT_ID:}
    # OIDC-only: sem client-secret
    # client-secret: (não utilizar)
    tenant-id: ${AZURE_TENANT_ID:}
    fallback-enabled: ${AZURE_KEYVAULT_FALLBACK:true}

# ===== SERVER CONFIGURATION =====
server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /rest/v1
  compression:
    enabled: true
  http2:
    enabled: true
