name: 'timeout-run'
description: 'Executa um comando com timeout e marca como falha se exceder o tempo especificado, então prossegue para o próximo step'
inputs:
  command:
    description: 'Comando shell a ser executado'
    required: true
  timeout-seconds:
    description: 'Tempo máximo em segundos antes de marcar falha'
    required: false
    default: '60'
runs:
  using: 'composite'
  steps:
    - name: 'Executar comando com timeout'
      shell: bash
      run: |
        set -euo pipefail

        COMANDO="${{ inputs.command }}"
        TIMEOUT_SEGUNDOS="${{ inputs.timeout-seconds }}"

        echo "🔄 Executando com timeout de ${TIMEOUT_SEGUNDOS}s: ${COMANDO}"

        # Executa o comando com timeout especificado
        if timeout "${TIMEOUT_SEGUNDOS}" bash -c "${COMANDO}"; then
          echo "✅ Comando executado com sucesso"
        else
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 124 ]; then
            echo "⏰ Timeout atingido após ${TIMEOUT_SEGUNDOS}s - marcando como falha e prosseguindo"
            exit 1
          else
            echo "❌ Comando falhou com código de saída: $EXIT_CODE"
            exit $EXIT_CODE
          fi
        fi
