name: 'timeout-run'
description: 'Executa um comando com timeout e marca como falha se exceder o tempo especificado, então proceed to next step'
inputs:
  command:
    description: 'Comando shell a ser executado'
    required: true
  timeout-seconds:
    description: 'Tempo máximo em segundos antes de marcar falha'
    required: false
    default: '60'
runs:
  using: 'composite'
  steps:
    - name: 'Run command with timeout'
      shell: bash
      run: |
        set -euo pipefail

        COMMAND="$1"
        TIMEOUT_SECONDS=${INPUT_TIMEOUT_SECONDS:-60}

        echo "Executando com timeout de ${TIMEOUT_SECONDS}s: ${INPUT_COMMAND}"

        # Ejecuta o comando em background e espera pelo timeout
        timeout "$TIMEOUT_SECONDS" bash -c "${INPUT_COMMAND}"
